
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: urls_shorter_development
  username: abukin
  password: 123

test:
  <<: *default
  database: urls_shorter_test
  username: abukin
  password: 123

production:
  <<: *default
  database: urls_shorter_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>